### ISSUE TITLE
Node deployment

### ISSUE THREAD

**Issue by GeekArthur** [annieke/rosetta-ethereum#14]
**Is your feature request related to a problem? Please describe.**
We need to implement a node deployment mechanism for rosetta implementation. Currently we have the following service need to build and deploy:
- Data transport layer: https://github.com/ethereum-optimism/optimism/tree/master/packages/data-transport-layer
- L2geth: https://github.com/ethereum-optimism/optimism/tree/master/l2geth
- L1 node: it needs to be deployed on Kovan testnet
- Rosetta server

**Describe the solution you'd like**
We have two solutions below and we need to do some research to figure out which one is easier to implement and more compatible with current rosetta infrastructure
1. Consolidate all services into one single container
2. One service per container (Use multiple containers)

**Additional context**
I have three concerns regarding the multiple containers solution and we might need to deep dive later:
1. rosetta-e2e: seems like currently there are no polygon related dockerfiles under rosetta-e2e, we need to figure out how to integrate multi-containers deployment into rosetta-e2e
2. services difference: I did a quick search on Polygon, the additional two containers are `Bor` and  `Heimdall`, which are Matic protocol implementation and validator node. We need to compare and confirm Optimism services (eg. data transport layer and l2geth) can do the same thing and there are no configuration and connection issues
3. op-replica: I think for local testing it’s fine, but for production, we still need to clone the specific repo (data transport layer or l2geth) separately and build from source

**Comment by Inphi** [comment]
We very much prefer a docker-compose setup for at least the ethereum-optimism deployment (so one service per container) for the following reasons:
1. l2geth and the data-transport-layer (dtl) have different failure domains. While the former relies on the latter for sequencing, it shouldn't have to also crash if the dtl goes offline. A single container approach isn't ideal for reliability as any failure will take down both components.
2. Both l2geth and the dtl have very different resource requirements. It'll be easier to appropriately provision both services if they run in separate containers.
3. Our existing deployment scripts for l2 replicas are already based on a multi-container setup via docker-compose. This makes it easier to deliver a dockerized setup to users while providing updates/bugfixes.

I think the first two points also apply to the Rosetta server and the L1 node. And we can provide a docker-compose setup that incorporates all four components. Does this work for you?

**Comment by GeekArthur** [comment]
@Inphi I agree with you, decoupling architecture has many advantages in terms of maintenance, debugging and reliability. Rosetta infrastructure also supports docker-compose setup, that's good for integration work as we already had op-replica as an example.

We need to figure out how to integrate the decoupling architecture into all the existing services of Rosetta (eg. rosetta-e2e). Currently my colleague Iris is working on this, I will bring her into the discussion and keep syncing up with her.

**Comment by irisZhangCB** [comment]
@Inphi I'm trying to set up node locally using docker-compose. Currently I can bring built-from-source l2geth, dtl and rosetta into this setup. but have some connection issues between dtl and l1node(using openethereum for kovan). One question I have is on what condition can dtl connect to l1node? Does l1node have to be fully synced? What endpoints does dtl calls and what will be the result?
I'm asking this because l1node usually can't show chainID when first syncing and i suspect this may be one of the reasons for connection failure.

Also, it would be really helpful if you can provide a docker-compose setup! I'll continue testing locally meanwhile.

**Comment by Inphi** [comment]
@irisZhangCB  The l1 node doesn't have to be fully synced. But it should have blocks produced on December post-regenesis (so at roughly block height 13720000).
What's your docker-compose setup like? Are you using [op-replica](https://github.com/optimisticben/op-replica/) as a base?

**Comment by irisZhangCB** [comment]
@Inphi  After local l1node has loaded snapshot, it can be connect by dtl! But healcheck and l2geth containers are not up. Sharing the errors below:
l2geth:
```
Fatal: Error starting protocol stack: Cannot initialize syncservice: Cannot initialize latest L1 data: Cannot fetch ctc deploy block at height 27989623: json: cannot unmarshal non-string into Go struct field EthContext.blockHash of type common.Hash
```

healthcheck:
```
{"level":30,"time":1643809977040,"msg":"Listening on port 3000"}

Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.4.4)

at Logger.makeError (/opt/optimism/node_modules/@ethersproject/logger/lib/index.js:187:21)

at Logger.throwError (/opt/optimism/node_modules/@ethersproject/logger/lib/index.js:196:20)

at StaticJsonRpcProvider.<anonymous> (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:491:54)

at step (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)

at Object.throw (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)

at rejected (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)

at processTicksAndRejections (internal/process/task_queues.js:95:5) {

reason: 'could not detect network',

code: 'NETWORK_ERROR',

event: 'noNetwork'

}
```
My docker-compose setup is based on op-replica, didn't change that much. For simplicity i'm using docker hub images instead of building from source. 
```
---
version: "3.4"
services:
  l1parity:
    image: openethereum/openethereum:latest
    command: '--chain=kovan --no-ancient-blocks --jsonrpc-port=8545 --jsonrpc-cors=all --jsonrpc-interface=all --jsonrpc-hosts=all --jsonrpc-apis=web3,eth,net,parity'
    ports:
      - "26656:26656"
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
  data-transport-layer:
    image: ethereumoptimism/data-transport-layer:latest
    restart: unless-stopped
    env_file:
      - ${SHARED_ENV_PATH}/data-transport-layer.env
      - .env
    volumes:
      - dtl:/db
    depends_on:
      - l1parity
  l2geth-replica:
    image: ethereumoptimism/l2geth:latest
    restart: unless-stopped
    entrypoint:
      - /bin/sh
      - -c
      #- "sleep infinity"
      - "/scripts/check-for-chaindata.sh && /scripts/l2geth-replica-start.sh"
    env_file:
      - ${SHARED_ENV_PATH}/l2geth-replica.env
      - .env
    volumes:
      - geth:/geth
      - ./kustomize/replica/bases/configmaps/:/scripts/
    depends_on:
      - l1parity
  replica-healthcheck:
    image: ethereumoptimism/replica-healthcheck:0.3.0
    restart: unless-stopped
    env_file:
      - kustomize/replica/envs/kovan/replica-healthcheck.env
      - .env
    volumes:
      - ./kustomize/replica/bases/configmaps/:/scripts/
volumes:
  dtl:
  geth:
```
